with open("SECURITY.md", "r") as f:
    content = f.read()

old_local_ai = """## Local AI
The Local AI runs as an unprivileged `jarvis` user in a hardened systemd service. It interacts with the system strictly through the JARVIS Tool Registry and Policy Engine, ensuring no uncontrolled access to the OS."""

new_local_ai = """## Local Emergency AI Security

The Local AI (Qwen3-1.7B) is treated as an untrusted intelligence source and is tightly sandboxed.

### 1. Process Hardening
The local inference engine runs as an unprivileged `jarvis` user in a hardened systemd service (`jarvis-local-ai.service`).
*   **Capabilities**: `NoNewPrivileges=true`, `ProtectSystem=strict`, `ProtectHome=true`, `PrivateTmp=true`.
*   **Filesystem**: The model file and `llama-server` binaries are strictly read-only to the daemon.

### 2. Sudoers Lifecycle Boundary
The JARVIS Core daemon needs to start/stop the local AI when cloud fallback triggers. It is granted explicit, locked-down `sudo` access only to `/usr/lib/jarvis/scripts/local-ai-lifecycle.sh`.
*   The script rigidly accepts only exactly `start`, `stop`, `restart`, or `status`.
*   Malicious injection attempts (e.g., `--exec bash`, `rm -rf`) are rejected by the script wrapper.

### 3. Tool Call Validation
The Policy Engine treats tool requests generated by the local AI identical to those from the cloud.
*   **Injection Resistance**: Any malformed JSON, unknown tool requests, or attempts to execute arbitrary shell commands inside `<tool_call>` boundaries are actively stripped and rejected by the AI Gateway before execution."""

if old_local_ai in content:
    content = content.replace(old_local_ai, new_local_ai)
    with open("SECURITY.md", "w") as f:
        f.write(content)
    print("Patched.")
else:
    print("Not found.")
