---
dontChroot: false
timeout: 60
script:
    - "userdel -f jarvis || true"
    - "rm -rf /home/jarvis || true"
    - "apt-get -y purge calamares calamares-settings-debian || true"
    - "apt-get -y autoremove || true"
