---
modules-search: [ local ]

instances:
- id:       default
  module:   branding
  config:
    branding: jarvis

sequence:
- show:
  - welcome
  - locale
  - keyboard
  - partition
  - users
  - summary
- exec:
  - partition
  - mount
  - unpackfs
  - machineid
  - fstab
  - locale
  - keyboard
  - localecfg
  - initramfs
  - networkcfg
  - hwclock
  - services-systemd
  - packages
  - displaymanager
  - grubcfg
  - bootloader
  - shellprocess
  - umount
- show:
  - finished

branding: jarvis
prompt-install: true
dont-chroot: false
oem-setup: false
